default['minecraft_service'] = "minecraft_server.jar"
default['minecraft_username'] = "minecraft"
default['minecraft_userpath'] = "/home/minecraft"
default['minecraft_world'] = "world"
default['minecraft_mcpath'] = "/home/minecraft/minecraft"
default['minecraft_backuppath'] = "/home/minecraft/minecraft.backup"
default['minecraft_cpu'] = "1"
default['minecraft_xms'] = "512M"
default['minecraft_server_motd'] = "Welcome to Chef Minecraft"
default['minecraft_server_whitelist'] = "true"

